# Generated by Django 3.1.6 on 2021-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fi_choice', models.CharField(max_length=100)),
                ('se_choice', models.CharField(max_length=100)),
                ('th_choice', models.CharField(max_length=100)),
                ('fo_choice', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
